name: E2E on Chrome

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - tests
      - cypress-wf
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build with Webpack
        run: npm run build
        env:
          BURGER_API_URL: ${{ secrets.BURGER_API_URL }}

      - name: Start application
        run: npm start &

      - name: Wait for application to be ready
        run: npx wait-on http://localhost:3000

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
